#!/usr/bin/env bash
# This is third script
for pid in /proc/[0-9]*; do
pid_num="${pid##*/}"
if [[ -r "$pid/comm" ]]; then
proc_name=$(<"$pid/comm")
if [[ "$proc_name" == *bash* ]]; then
            echo "PID: $pid_num - Process Name: $proc_name"
        fi
    fi
done
