#!/usr/bin/env bash
# This is third script
for pid in /proc/[0-9]*; do
    if [[ -r "$pid/comm" ]]; then
        name=$(<"$pid/comm")
        if [[ "$name" == "bash" ]]; then
            echo "${pid##*/} $name"
        fi
    fi
done
